---

- hosts: control
  gather_facts: no
  tasks:

  - name: Install python
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- hosts: control

  vars:
    harness_directory: "{{ ansible_env.HOME }}/harness"

  tasks:

  - name: Add Ansible Repo
    become: yes
    apt_repository: repo=ppa:ansible/ansible

  - name: Install APT Packages
    become: yes
    apt: name={{ item }} update_cache=yes
    with_items:
    - software-properties-common
    - zip
    - unzip
    - python-pip
    - python-netaddr
    - ansible

  - name: Install Cryptography for Vault Performance
    pip: name=cryptography

  - name: Create Harness Directories
    file: path={{ item }} state=directory
    with_items:
    - "{{ harness_directory }}"
    - "{{ harness_directory }}/playbooks"
    - "{{ harness_directory }}/playbooks/templates"

  - name: Copy Ansible Files
    copy: src={{ item.src }} dest={{ harness_directory }}/{{ item.dest }} mode=600
    with_items:
    - src:  templates
      dest: playbooks/
    - src:  bootstrap-cluster.yml
      dest: playbooks/bootstrap-cluster.yml
    - src:  install-nomad.yml
      dest: playbooks/install-nomad.yml
    - src:  requirements.yml
      dest: playbooks/requirements.yml
    - src:  vars.yml
      dest: playbooks/vars.yml
    - src:  ../inventory
      dest: inventory
    - src:  ../ansible.cfg
      dest: ansible.cfg
    - src:  checkbox_deploy.yml
      dest: playbooks/checkbox_deploy.yml
    - src:  "{{ ansible_env.HOME }}/.ssh/my_key.pem"
      dest: "{{ ansible_env.HOME }}/.ssh/my_key.pem" 

  - name: Install Roles
    command: ansible-galaxy install -r {{ harness_directory }}/playbooks/requirements.yml
